/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module store16_6 (
    input clk,
    input rst,
    input stcom,
    input [15:0] inp,
    output reg [15:0] out
  );
  
  
  
  reg [15:0] M_register_1_d, M_register_1_q = 1'h0;
  
  always @* begin
    M_register_1_d = M_register_1_q;
    
    if (stcom) begin
      M_register_1_d = inp;
    end
    out = M_register_1_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_register_1_q <= 1'h0;
    end else begin
      M_register_1_q <= M_register_1_d;
    end
  end
  
endmodule
